version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/praqma/native-example-conan
    steps:
      - checkout
      - run:
          name: Version
          command: |
            set -x
            go version
      - run:
          name: Update & Upgrade
          command: |
            set -x
            sudo apt-get update
            sudo apt-get upgrade
      - run:
          name: Interpolating Environment Variables to Set Other Environment Variables
          # If you need to interpolate other environment variables to set an environment variable, the only place to do this at the moment is in bash.
          # CircleCI 2.0 automatically sets a $BASH_ENV variable to a random name in /tmp, and will source this file for each step.
          # https://circleci.com/docs/2.0/env-vars/#interpolating-environment-variables-to-set-other-environment-variables
          command: |
            echo 'export DEBIAN_FRONTEND=noninteractive' >> $BASH_ENV
            echo 'export THIRDPARTY_DIR=${PWD}/3rdparty' >> $BASH_ENV
            echo 'export EXAMPLE_POCO_TIMER_DIR=${THIRDPARTY_DIR}/example-poco-timer-master' >> $BASH_ENV
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
            ls -al ${PWD}
            ls -al ${EXAMPLE_POCO_TIMER_DIR}
      - run:
          name: Setup Make Prerequisites
          command: |
            set -x
            echo "Setup Make Prerequisites ..."
            sudo apt-get install --yes build-essential
            gcc --version
      - run:
          name: Get Submodule(s)
          command: |
            git submodule init
            git submodule update
      - run:
          name: Setup
          command: |
            set -x
            curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
            python /tmp/get-pip.py --user
            pip install --user pipenv
            pip install --user conan
            conan --version
            sudo apt-get install --yes cmake
            cmake --version
      - run:
          name: Build
          command: |
            set -x
            mkdir build && cd build
            conan install ${EXAMPLE_POCO_TIMER_DIR} -s compiler=gcc -s compiler.version=6.3 -s compiler.libcxx=libstdc++11
            cmake ${EXAMPLE_POCO_TIMER_DIR} -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
            cmake --build ${PWD}
            ${PWD}/bin/timer
      - run:
          name: Details
          command: |
            set -x
            conan search
            conan search Poco/1.7.8p3@pocoproject/stable
            conan search zlib/1.2.11@conan/stable --table=build/onan_search_table.html -r=conan-center
            conan info 3rdparty/example-poco-timer-master --graph=build/conan_info_graph.html
      - run:
          name: Run
          command: |
            set -x
            ${PWD}/build/bin/timer
      - store_artifacts:
          path: build
  test:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/praqma/native-example-conan
    steps:
      - checkout
      - run:
          name: Interpolating Environment Variables to Set Other Environment Variables
          # If you need to interpolate other environment variables to set an environment variable, the only place to do this at the moment is in bash.
          # CircleCI 2.0 automatically sets a $BASH_ENV variable to a random name in /tmp, and will source this file for each step.
          # https://circleci.com/docs/2.0/env-vars/#interpolating-environment-variables-to-set-other-environment-variables
          command: |
            echo 'export DEBIAN_FRONTEND=noninteractive' >> $BASH_ENV
            echo 'export THIRDPARTY_DIR=${PWD}/3rdparty' >> $BASH_ENV
            echo 'export EXAMPLE_POCO_TIMER_DIR=${THIRDPARTY_DIR}/example-poco-timer-master' >> $BASH_ENV
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
            ls -al ${PWD}
            ls -al ${EXAMPLE_POCO_TIMER_DIR}
      - run:
          name: Update & Upgrade
          command: |
            set -x
            sudo apt-get update
            sudo apt-get upgrade
      - run:
          name: Check Version
          command: |
            set -x
            go version
      - run:
          name: Setup Make Prerequisites
          command: |
            set -x
            echo "Setup Make Prerequisites ..."
            sudo apt-get install --yes build-essential
            gcc --version
      - run:
          name: Get Submodule(s)
          command: |
            git submodule init
            git submodule update
      - run:
          name: Setup
          command: |
            set -x
            curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
            python /tmp/get-pip.py --user
            pip install --user pipenv
            pip install --user conan
            conan --version
            sudo apt-get install --yes cmake
            cmake --version
      - run:
          name: Build
          command: |
            set -x
            mkdir build && cd build
            conan install ${EXAMPLE_POCO_TIMER_DIR} -s compiler=gcc -s compiler.version=6.3 -s compiler.libcxx=libstdc++11
            cmake ${EXAMPLE_POCO_TIMER_DIR} -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
            cmake --build ${PWD}
            ${PWD}/bin/timer
      - run:
          name: Details
          command: |
            set -x
            conan search
            conan search Poco/1.7.8p3@pocoproject/stable
            conan search zlib/1.2.11@conan/stable --table=build/onan_search_table.html -r=conan-center
            conan info 3rdparty/example-poco-timer-master --graph=build/conan_info_graph.html
      - run:
          name: Run
          command: |
            set -x
            ${PWD}/build/bin/timer
      - store_artifacts:
          path: build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
