version: 2
jobs:
  build:
    docker:
      - image: praqma/native-conan:latest
    working_directory: ~/praqma/native-example-conan
    steps:
      - checkout
      - run:
          name: Version
          command: |
            set -x
            cat /etc/*release
      - run:
          name: Run Container
          command: ${PWD}/build-ci.sh
  test:
    docker:
      - image: praqma/native-conan:latest
    working_directory: ~/praqma/native-example-conan
    steps:
      - checkout
      - run:
          name: Check Version
          command: |
            set -x
            cat /etc/*release
      - run:
          name: Build Docker Image
          command: ${PWD}/dockerize.sh
      - run:
          name: Run Container
          command: ${PWD}/containerize-ci-build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
