version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:jdk
    working_directory: ~/sheeeng/omed-conan
    steps:
      - checkout
      - run:
          name: Interpolating Environment Variables to Set Other Environment Variables
          # If you need to interpolate other environment variables to set an environment variable, the only place to do this at the moment is in bash.
          # CircleCI 2.0 automatically sets a $BASH_ENV variable to a random name in /tmp, and will source this file for each step.
          # https://circleci.com/docs/2.0/env-vars/#interpolating-environment-variables-to-set-other-environment-variables
          command: |
            echo 'export DEBIAN_FRONTEND=noninteractive' >> $BASH_ENV
            echo 'export THIRDPARTY_DIR=${PWD}/3rdparty' >> $BASH_ENV
            echo 'export EXAMPLE_POCO_TIMER_DIR=${THIRDPARTY_DIR}/example-poco-timer-master' >> $BASH_ENV
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Update & Upgrade
          command: |
            set -x
            sudo apt-get update
            sudo apt-get upgrade
      - run:
          name: Check Version
          command: |
            set -x
            java -version
      - run:
          name: Setup Make Prerequisites
          command: |
            set -x
            echo "Setup Make Prerequisites ..."
            sudo apt-get install --yes build-essential
            gcc --version
      - run:
          name: Get Submodule(s)
          command: |
            git submodule init
            git submodule update
      - run:
          name: Setup Conan
          command: |
            set -x
            curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
            python /tmp/get-pip.py --user
            pip install --user pipenv
            pip install --user conan
            cp bak/timer.cpp ${EXAMPLE_POCO_TIMER_DIR}
            cp bak/conanfile.txt ${EXAMPLE_POCO_TIMER_DIR}
            conan --version
            conan install ${EXAMPLE_POCO_TIMER_DIR}
  test:
    docker:
      - image: circleci/openjdk:jdk
    working_directory: ~/sheeeng/omed-conan
    steps:
      - checkout
      - run:
          name: Interpolating Environment Variables to Set Other Environment Variables
          # If you need to interpolate other environment variables to set an environment variable, the only place to do this at the moment is in bash.
          # CircleCI 2.0 automatically sets a $BASH_ENV variable to a random name in /tmp, and will source this file for each step.
          # https://circleci.com/docs/2.0/env-vars/#interpolating-environment-variables-to-set-other-environment-variables
          command: |
            echo 'export DEBIAN_FRONTEND=noninteractive' >> $BASH_ENV
            echo 'export THIRDPARTY_DIR=${PWD}/3rdparty' >> $BASH_ENV
            echo 'export GSON_DIR=${THIRDPARTY_DIR}/gson-master' >> $BASH_ENV
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Update & Upgrade
          command: |
            set -x
            sudo apt-get update
            sudo apt-get upgrade
      - run:
          name: Check Version
          command: |
            set -x
            java -version
      - run:
          name: Setup Make Prerequisites
          command: |
            set -x
            echo "Setup Make Prerequisites ..."
            sudo apt-get install --yes build-essential
            gcc --version
      - run:
          name: Get Submodule(s)
          command: |
            git submodule init
            git submodule update
      - run:
          name: Setup Conan
          command: |
            set -x
            curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
            python /tmp/get-pip.py --user
            pip install --user pipenv
            pip install --user conan
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
